# Generated by Django 6.0 on 2025-12-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('text_en', models.TextField(blank=True)),
                ('address_en', models.CharField(blank=True, max_length=300)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('text_uk', models.TextField(blank=True)),
                ('address_uk', models.CharField(blank=True, max_length=300)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('text_ru', models.TextField(blank=True)),
                ('address_ru', models.CharField(blank=True, max_length=300)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.CharField(blank=True, max_length=255)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('subtitle_uk', models.CharField(blank=True, max_length=300)),
                ('body_uk', models.TextField(blank=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('subtitle_ru', models.CharField(blank=True, max_length=300)),
                ('body_ru', models.TextField(blank=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('text_en', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.CharField(blank=True, max_length=255)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('subtitle_uk', models.CharField(blank=True, max_length=500)),
                ('text_uk', models.TextField(blank=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('subtitle_ru', models.CharField(blank=True, max_length=500)),
                ('text_ru', models.TextField(blank=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.service')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/%Y/%m/')),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('alt_uk', models.CharField(blank=True, max_length=200)),
                ('alt_ru', models.CharField(blank=True, max_length=200)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.servicearticle')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/%Y/%m/')),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('alt_uk', models.CharField(blank=True, max_length=200)),
                ('alt_ru', models.CharField(blank=True, max_length=200)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.service')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
