# Generated by Django 6.0.5 on 2026-06-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.CharField(blank=True, max_length=255)),
                ('title_uk', models.CharField(blank=True, max_length=255)),
                ('subtitle_uk', models.CharField(blank=True, max_length=500)),
                ('body_uk', models.TextField(blank=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('subtitle_ru', models.CharField(blank=True, max_length=500)),
                ('body_ru', models.TextField(blank=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp')], default='phone', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(blank=True, max_length=500)),
                ('answer_en', models.TextField(blank=True)),
                ('question_uk', models.CharField(blank=True, max_length=500)),
                ('answer_uk', models.TextField(blank=True)),
                ('question_ru', models.CharField(blank=True, max_length=500)),
                ('answer_ru', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('features_en', models.TextField(blank=True, help_text='One feature per line')),
                ('price_display_en', models.CharField(blank=True, max_length=100)),
                ('name_uk', models.CharField(blank=True, max_length=200)),
                ('description_uk', models.TextField(blank=True)),
                ('features_uk', models.TextField(blank=True, help_text='One feature per line')),
                ('price_display_uk', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('description_ru', models.TextField(blank=True)),
                ('features_ru', models.TextField(blank=True, help_text='One feature per line')),
                ('price_display_ru', models.CharField(blank=True, max_length=100)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('body_en', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.CharField(blank=True, max_length=255)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('subtitle_uk', models.CharField(blank=True, max_length=300)),
                ('body_uk', models.TextField(blank=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('subtitle_ru', models.CharField(blank=True, max_length=300)),
                ('body_ru', models.TextField(blank=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username (without @) or full t.me link', max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='viber',
            field=models.CharField(blank=True, help_text='Phone number in international format', max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Phone number in international format', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicearticleimage',
            name='image',
            field=models.ImageField(upload_to='service_articles/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='SectionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('text_en', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.CharField(blank=True, max_length=255)),
                ('title_uk', models.CharField(blank=True, max_length=200)),
                ('subtitle_uk', models.CharField(blank=True, max_length=500)),
                ('text_uk', models.TextField(blank=True)),
                ('seo_title_uk', models.CharField(blank=True, max_length=255)),
                ('seo_description_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('subtitle_ru', models.CharField(blank=True, max_length=500)),
                ('text_ru', models.TextField(blank=True)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255)),
                ('seo_description_ru', models.CharField(blank=True, max_length=255)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.section')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section_articles/%Y/%m/')),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('alt_uk', models.CharField(blank=True, max_length=200)),
                ('alt_ru', models.CharField(blank=True, max_length=200)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.sectionarticle')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/%Y/%m/')),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('alt_uk', models.CharField(blank=True, max_length=200)),
                ('alt_ru', models.CharField(blank=True, max_length=200)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.section')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
